feat(kafka): Added exceptions to consumer producer, added transaction pool messages
ateliware/spring-webflux-scylla pull request #1
Opened 2019-06-27 14:14 UTC by allansduarte

2019-06-27 15:05 UTC, lucascvidal approved these changes

2019-06-28 18:57 UTC, wantero requested changes
@allansduarte você conseguiu testar essas suas alterações no seu ambiente? Aqui está gerando erro ao testar com suas alterações.

Seguem abaixo prints:

Antes da PR:
<img width="1056" alt="Screen Shot 2019-06-28 at 15 48 54" src="https://user-images.githubusercontent.com/12854717/60364669-2d562600-99bd-11e9-9f2a-1c9dcee16d29.png">

Erro da PR no Postman:
<img width="1375" alt="Screen Shot 2019-06-28 at 15 51 23" src="https://user-images.githubusercontent.com/12854717/60364681-3515ca80-99bd-11e9-9c08-00f7227db1bf.png">

Erro da PR no Java:
<img width="1665" alt="Screen Shot 2019-06-28 at 15 51 50" src="https://user-images.githubusercontent.com/12854717/60364699-3e069c00-99bd-11e9-9ace-77e74e129914.png">

2019-06-28 19:51 UTC, allansduarte commented
@wantero Foi adicionado suporte para transactions no projeto, padrão agora, então todo kafka listener , que não usa transactions precisa de @Transactional. Kafka listener com transactions não é necessário. Também foi feito uma refatoração no KafkaController.

2019-06-28 20:01 UTC, wantero approved these changes
Aprovado!

2019-06-28 20:02 UTC, merged